### PR TITLE
Backend logic and nodemailer

### PR DESCRIPTION
**Pull request by alasalle**
# Description
Created mutations for:
rating projects
reviewing projects
liking reviews
disliking reviews
creating a user (w/ nodemailer)
creating review(w/ nodemailer)
creating project

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change status

- [ ] Complete, tested, ready to review and merge
- [x] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by alasalle** [comment]
[3rd party APIs & Service integrations](https://trello.com/c/W03pWO8D/25-3rd-party-apis-service-integrations)

**Comment by alasalle** [comment]
[Create/Edit Project Page](https://trello.com/c/KDZDxoGQ/10-create-edit-project-page)

**Comment by alasalle** [comment]
[Project List](https://trello.com/c/8Q9zkam5/8-project-list)

**Comment by alasalle** [comment]
[Review Modal Window](https://trello.com/c/uH4O66Lx/16-review-modal-window)

**Comment by mtrew2015** [comment]
[SendGrid API / NodeMailer](https://trello.com/c/oA7TluCm/63-sendgrid-api-nodemailer)

**Pull request merged**
