### PR TITLE
Projects Page and Reviews Page

### PR DESCRIPTION
**Pull request by alasalle**
# Description

Adds a basic projects page which can pull in user projects. Will need to uncomment the localStorage code when create project functionality is complete and I can reset and repopulate the database with real users/projects" Adds a basic reviews page.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change status

- [ ] Complete, tested, ready to review and merge
- [x] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by alasalle** [comment]
[Project List](https://trello.com/c/8Q9zkam5/8-project-list)

**Comment by alasalle** [comment]
[Review List Page (Empty)](https://trello.com/c/793T3XoM/11-review-list-page-empty)

**Comment by alasalle** [comment]
[Review List Page (Empty)](https://trello.com/c/GZAWFzbN/12-review-list-page-empty)

**Comment by alasalle** [comment]
[Review List Page (Not-Empty)](https://trello.com/c/RJ170Ozm/13-review-list-page-not-empty)

**Comment by mtrew2015** [comment]
[Create/Edit Project Page](https://trello.com/c/KDZDxoGQ/10-create-edit-project-page)

**Pull request merged**
